/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.UI;

import com.myproject.Form.Form_QLYNHANVIEN;
import com.myproject.Form.Form_QLYSANPHAM;

import com.myproject.Form.Form_THONGKE;
import com.myproject.Form.Form_TINHLUONG;
import com.toedter.calendar.demo.DemoTable;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class Dashboard extends javax.swing.JFrame {
    
    private Form_QLYNHANVIEN form_qlynhanvien;
    private Form_QLYSANPHAM form_qlysanpham;
    private Form_TINHLUONG form_tinhluong;
    private Form_THONGKE form_thongke;
    /**
     * Creates new form Dashboard
     */

    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
        CreatePanel();
        setFullScreen();
        setWindowSize();
    }
    
    void CreatePanel(){
        form_qlynhanvien = new Form_QLYNHANVIEN();
        form_qlysanpham = new Form_QLYSANPHAM();
        form_thongke = new Form_THONGKE();
        form_tinhluong = new Form_TINHLUONG();

    }
    void setFullScreen() {
//        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
//        GraphicsDevice gd = ge.getDefaultScreenDevice();
//        if (gd.isFullScreenSupported()) {
//            gd.setFullScreenWindow(this);
//        } else {
//            System.err.println("Full-screen mode is not supported");
//        }
//        int menuWidth = 270;
//        int navbarHeight = 90;
//        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        
//        
//        int remainingWidth = screenSize.width - menuWidth;
//        int remainingHeight = screenSize.height - navbarHeight;
//        System.out.println(remainingWidth);
//        System.out.println(remainingHeight);
//        SPanel_Main.setPreferredSize(new Dimension(remainingWidth, screenSize.height));
//     
    }
 void setWindowSize() {
    int fixedWidth = 1100;
    int menuWidth = 270;
    int navbarHeight = 90;
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    
    int remainingHeight = screenSize.height - navbarHeight;
    System.out.println(fixedWidth);
    System.out.println(remainingHeight);
    this.setBackground(new Color(255,255,255));
    // Set the size of the main window
    this.setSize(new Dimension(fixedWidth + menuWidth, screenSize.height));
    panelHeader.setSize(new Dimension(1200, navbarHeight));
    // Set the preferred size of SPanel_Main
    SPanel_Main.setPreferredSize(new Dimension(fixedWidth, screenSize.height));
    // If you want to center the window on the screen
    this.setLocationRelativeTo(null);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_qlynhanvien = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btn_thongke = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btn_tinhluong = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_qlysanpham = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_qlynhanvien1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        SPanel_Main = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1930, 1023));
        setSize(new java.awt.Dimension(1930, 1023));

        panelHeader.setBackground(new java.awt.Color(207, 115, 115));
        panelHeader.setMinimumSize(new java.awt.Dimension(1600, 80));
        panelHeader.setPreferredSize(new java.awt.Dimension(1930, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/icons8_menu_48px_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 45)); // NOI18N
        jLabel2.setText("l");

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HELIUM MEDIA");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/search_26px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 45)); // NOI18N
        jLabel5.setText("l");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/bell_26px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 45)); // NOI18N
        jLabel7.setText("l");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/group_message_26px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/male_user_50px.png"))); // NOI18N
        jLabel9.setText("Hello Admin");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(381, 381, 381)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(64, 64, 64)
                .addComponent(jLabel9))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelHeaderLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelHeaderLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelHeaderLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelHeaderLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelHeaderLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelHeaderLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel9)))
                    .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(115, 105, 105));

        btn_qlynhanvien.setBackground(new java.awt.Color(165, 116, 116));
        btn_qlynhanvien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_qlynhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_qlynhanvienMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("QUẢN LÝ NHÂN VIÊN");

        javax.swing.GroupLayout btn_qlynhanvienLayout = new javax.swing.GroupLayout(btn_qlynhanvien);
        btn_qlynhanvien.setLayout(btn_qlynhanvienLayout);
        btn_qlynhanvienLayout.setHorizontalGroup(
            btn_qlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_qlynhanvienLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        btn_qlynhanvienLayout.setVerticalGroup(
            btn_qlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_qlynhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_thongke.setBackground(new java.awt.Color(165, 116, 116));
        btn_thongke.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_thongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_thongkeMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("THỐNG KÊ");

        javax.swing.GroupLayout btn_thongkeLayout = new javax.swing.GroupLayout(btn_thongke);
        btn_thongke.setLayout(btn_thongkeLayout);
        btn_thongkeLayout.setHorizontalGroup(
            btn_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_thongkeLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(73, 73, 73))
        );
        btn_thongkeLayout.setVerticalGroup(
            btn_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_thongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_tinhluong.setBackground(new java.awt.Color(165, 116, 116));
        btn_tinhluong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tinhluong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tinhluongMouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TÍNH LƯƠNG");

        javax.swing.GroupLayout btn_tinhluongLayout = new javax.swing.GroupLayout(btn_tinhluong);
        btn_tinhluong.setLayout(btn_tinhluongLayout);
        btn_tinhluongLayout.setHorizontalGroup(
            btn_tinhluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_tinhluongLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(53, 53, 53))
        );
        btn_tinhluongLayout.setVerticalGroup(
            btn_tinhluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_tinhluongLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_qlysanpham.setBackground(new java.awt.Color(165, 116, 116));
        btn_qlysanpham.setForeground(new java.awt.Color(255, 255, 255));
        btn_qlysanpham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_qlysanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_qlysanphamMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("QUẢN LÝ SẢN PHẨM");

        javax.swing.GroupLayout btn_qlysanphamLayout = new javax.swing.GroupLayout(btn_qlysanpham);
        btn_qlysanpham.setLayout(btn_qlysanphamLayout);
        btn_qlysanphamLayout.setHorizontalGroup(
            btn_qlysanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_qlysanphamLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btn_qlysanphamLayout.setVerticalGroup(
            btn_qlysanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_qlysanphamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_exit.setBackground(new java.awt.Color(165, 116, 116));
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/icons8-exit-30.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("THOÁT");

        javax.swing.GroupLayout btn_exitLayout = new javax.swing.GroupLayout(btn_exit);
        btn_exit.setLayout(btn_exitLayout);
        btn_exitLayout.setHorizontalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_exitLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(69, 69, 69))
        );
        btn_exitLayout.setVerticalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_exitLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_exitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_qlynhanvien1.setBackground(new java.awt.Color(165, 116, 116));
        btn_qlynhanvien1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_qlynhanvien1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_qlynhanvien1MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ĐĂNG XUẤT");

        javax.swing.GroupLayout btn_qlynhanvien1Layout = new javax.swing.GroupLayout(btn_qlynhanvien1);
        btn_qlynhanvien1.setLayout(btn_qlynhanvien1Layout);
        btn_qlynhanvien1Layout.setHorizontalGroup(
            btn_qlynhanvien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_qlynhanvien1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(64, 64, 64))
        );
        btn_qlynhanvien1Layout.setVerticalGroup(
            btn_qlynhanvien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_qlynhanvien1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_tinhluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_qlysanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_qlynhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_qlynhanvien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btn_tinhluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btn_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btn_qlysanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btn_qlynhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btn_qlynhanvien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        SPanel_Main.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SPanel_Main, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SPanel_Main)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_qlynhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qlynhanvienMouseClicked
        setButtonColor(btn_qlynhanvien, form_qlynhanvien);
    }//GEN-LAST:event_btn_qlynhanvienMouseClicked

    private void btn_tinhluongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tinhluongMouseClicked
        setButtonColor(btn_tinhluong, form_tinhluong);
    }//GEN-LAST:event_btn_tinhluongMouseClicked

    private void btn_qlysanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qlysanphamMouseClicked
        setButtonColor(btn_qlysanpham, form_qlysanpham);
    }//GEN-LAST:event_btn_qlysanphamMouseClicked

    private void btn_thongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thongkeMouseClicked
        setButtonColor(btn_thongke, form_thongke);
    }//GEN-LAST:event_btn_thongkeMouseClicked

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_qlynhanvien1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qlynhanvien1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_qlynhanvien1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane SPanel_Main;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JPanel btn_qlynhanvien;
    private javax.swing.JPanel btn_qlynhanvien1;
    private javax.swing.JPanel btn_qlysanpham;
    private javax.swing.JPanel btn_thongke;
    private javax.swing.JPanel btn_tinhluong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelHeader;
    // End of variables declaration//GEN-END:variables


    public void setButtonColor(javax.swing.JPanel selectedButton, JPanel panelShow){
        Color selectColor = new Color(104, 37, 37);
        Color defaultColor = new Color(165,116,116);
        
        btn_qlynhanvien.setBackground(defaultColor);
        btn_qlysanpham.setBackground(defaultColor);
        btn_thongke.setBackground(defaultColor);
        btn_tinhluong.setBackground(defaultColor);
        selectedButton.setBackground(selectColor);
        SPanel_Main.setViewportView(panelShow);
        
}



}


