/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.UI;

import com.myproject.Form.Form_QLYNHANVIEN;
import com.myproject.Form.Form_QLYSANPHAM;
import com.myproject.Form.Form_THONGKE;
import com.myproject.Form.Form_TINHLUONG;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class test1 extends javax.swing.JFrame {

    private Form_QLYNHANVIEN form_qlynhanvien;
    private Form_QLYSANPHAM form_qlysanpham;
    private Form_TINHLUONG form_tinhluong;
    private Form_THONGKE form_thongke;

    /**
     * Creates new form test1
     */
    public test1() {
        initComponents();
        setLocationRelativeTo(null);
        CreatePanel();
        setWindowSize();
    }

    void setWindowSize() {
        int fixedWidth = 1100;
        int menuWidth = 270;
        int navbarHeight = 90;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        int remainingHeight = screenSize.height - navbarHeight;
        System.out.println(fixedWidth);
        System.out.println(remainingHeight);

        // Set the size of the main window
        this.setSize(new Dimension(fixedWidth + menuWidth, screenSize.height));

        this.setLocationRelativeTo(null);
    }

    void CreatePanel() {
        form_qlynhanvien = new Form_QLYNHANVIEN();
        form_qlysanpham = new Form_QLYSANPHAM();
        form_thongke = new Form_THONGKE();
        form_tinhluong = new Form_TINHLUONG();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SPanel_Main = new javax.swing.JScrollPane();
        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_qlynhanvien = new javax.swing.JPanel();
        lbl_qlynhanvien = new javax.swing.JLabel();
        btn_thongke = new javax.swing.JPanel();
        lbl_thongke = new javax.swing.JLabel();
        btn_tinhluong = new javax.swing.JPanel();
        lbl_tinhluong = new javax.swing.JLabel();
        btn_qlysanpham = new javax.swing.JPanel();
        lbl_qlysanpham = new javax.swing.JLabel();
        btn_exit = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JPanel();
        lbl_dangxuat = new javax.swing.JLabel();
        Panel_Main = new javax.swing.JPanel();

        SPanel_Main.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(204, 0, 51));
        panelHeader.setMinimumSize(new java.awt.Dimension(1600, 80));
        panelHeader.setPreferredSize(new java.awt.Dimension(1930, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/icons8_menu_48px_1.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 45)); // NOI18N
        jLabel2.setText("l");

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HELIUM MEDIA");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/search_26px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 45)); // NOI18N
        jLabel5.setText("l");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/bell_26px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 45)); // NOI18N
        jLabel7.setText("l");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/group_message_26px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/male_user_50px.png"))); // NOI18N
        jLabel9.setText("Hello Admin");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addGap(592, 592, 592)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        btn_qlynhanvien.setBackground(new java.awt.Color(51, 51, 51));
        btn_qlynhanvien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_qlynhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_qlynhanvienMouseClicked(evt);
            }
        });

        lbl_qlynhanvien.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lbl_qlynhanvien.setForeground(new java.awt.Color(153, 153, 153));
        lbl_qlynhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/add_user_group_woman_man_24px.png"))); // NOI18N
        lbl_qlynhanvien.setText("Quản lý nhân viên");

        javax.swing.GroupLayout btn_qlynhanvienLayout = new javax.swing.GroupLayout(btn_qlynhanvien);
        btn_qlynhanvien.setLayout(btn_qlynhanvienLayout);
        btn_qlynhanvienLayout.setHorizontalGroup(
            btn_qlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_qlynhanvienLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lbl_qlynhanvien)
                .addGap(36, 36, 36))
        );
        btn_qlynhanvienLayout.setVerticalGroup(
            btn_qlynhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_qlynhanvienLayout.createSequentialGroup()
                .addComponent(lbl_qlynhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_thongke.setBackground(new java.awt.Color(51, 51, 51));
        btn_thongke.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_thongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_thongkeMouseClicked(evt);
            }
        });

        lbl_thongke.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lbl_thongke.setForeground(new java.awt.Color(153, 153, 153));
        lbl_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/template_26px.png"))); // NOI18N
        lbl_thongke.setText("Thống kê");

        javax.swing.GroupLayout btn_thongkeLayout = new javax.swing.GroupLayout(btn_thongke);
        btn_thongke.setLayout(btn_thongkeLayout);
        btn_thongkeLayout.setHorizontalGroup(
            btn_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_thongkeLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lbl_thongke)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_thongkeLayout.setVerticalGroup(
            btn_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_thongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_thongke, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_tinhluong.setBackground(new java.awt.Color(0, 0, 0));
        btn_tinhluong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tinhluong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tinhluongMouseClicked(evt);
            }
        });

        lbl_tinhluong.setBackground(new java.awt.Color(255, 255, 255));
        lbl_tinhluong.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lbl_tinhluong.setForeground(new java.awt.Color(204, 0, 51));
        lbl_tinhluong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/edit_property_24px.png"))); // NOI18N
        lbl_tinhluong.setText("Tính lương");

        javax.swing.GroupLayout btn_tinhluongLayout = new javax.swing.GroupLayout(btn_tinhluong);
        btn_tinhluong.setLayout(btn_tinhluongLayout);
        btn_tinhluongLayout.setHorizontalGroup(
            btn_tinhluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_tinhluongLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lbl_tinhluong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_tinhluongLayout.setVerticalGroup(
            btn_tinhluongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_tinhluong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        btn_qlysanpham.setBackground(new java.awt.Color(51, 51, 51));
        btn_qlysanpham.setForeground(new java.awt.Color(255, 255, 255));
        btn_qlysanpham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_qlysanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_qlysanphamMouseClicked(evt);
            }
        });

        lbl_qlysanpham.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lbl_qlysanpham.setForeground(new java.awt.Color(153, 153, 153));
        lbl_qlysanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/categorize_24px.png"))); // NOI18N
        lbl_qlysanpham.setText("Quản lý sản phẩm");

        javax.swing.GroupLayout btn_qlysanphamLayout = new javax.swing.GroupLayout(btn_qlysanpham);
        btn_qlysanpham.setLayout(btn_qlysanphamLayout);
        btn_qlysanphamLayout.setHorizontalGroup(
            btn_qlysanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_qlysanphamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_qlysanpham)
                .addGap(43, 43, 43))
        );
        btn_qlysanphamLayout.setVerticalGroup(
            btn_qlysanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_qlysanpham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        btn_exit.setBackground(new java.awt.Color(51, 51, 51));
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/icons8-exit-30.png"))); // NOI18N
        jLabel15.setText("Thoát");

        javax.swing.GroupLayout btn_exitLayout = new javax.swing.GroupLayout(btn_exit);
        btn_exit.setLayout(btn_exitLayout);
        btn_exitLayout.setHorizontalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_exitLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_exitLayout.setVerticalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_exitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_logout.setBackground(new java.awt.Color(51, 51, 51));
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });

        lbl_dangxuat.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        lbl_dangxuat.setForeground(new java.awt.Color(153, 153, 153));
        lbl_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/myproject/Image/sort_window_24px.png"))); // NOI18N
        lbl_dangxuat.setText("Đăng xuất");

        javax.swing.GroupLayout btn_logoutLayout = new javax.swing.GroupLayout(btn_logout);
        btn_logout.setLayout(btn_logoutLayout);
        btn_logoutLayout.setHorizontalGroup(
            btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_logoutLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lbl_dangxuat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_logoutLayout.setVerticalGroup(
            btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_dangxuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_tinhluong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_qlysanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_qlynhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btn_thongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_tinhluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_qlysanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_qlynhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Main.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Panel_MainLayout = new javax.swing.GroupLayout(Panel_Main);
        Panel_Main.setLayout(Panel_MainLayout);
        Panel_MainLayout.setHorizontalGroup(
            Panel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        Panel_MainLayout.setVerticalGroup(
            Panel_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panel_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_qlynhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qlynhanvienMouseClicked
        setButtonColor(btn_qlynhanvien, lbl_qlynhanvien, form_qlynhanvien);
    }//GEN-LAST:event_btn_qlynhanvienMouseClicked

    private void btn_thongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thongkeMouseClicked
        setButtonColor(btn_thongke, lbl_thongke, form_thongke);
    }//GEN-LAST:event_btn_thongkeMouseClicked

    private void btn_tinhluongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tinhluongMouseClicked
        setButtonColor(btn_tinhluong, lbl_tinhluong, form_tinhluong);
    }//GEN-LAST:event_btn_tinhluongMouseClicked

    private void btn_qlysanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qlysanphamMouseClicked
        setButtonColor(btn_qlysanpham, lbl_qlysanpham, form_qlysanpham);
    }//GEN-LAST:event_btn_qlysanphamMouseClicked

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Main;
    private javax.swing.JScrollPane SPanel_Main;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JPanel btn_logout;
    private javax.swing.JPanel btn_qlynhanvien;
    private javax.swing.JPanel btn_qlysanpham;
    private javax.swing.JPanel btn_thongke;
    private javax.swing.JPanel btn_tinhluong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_dangxuat;
    private javax.swing.JLabel lbl_qlynhanvien;
    private javax.swing.JLabel lbl_qlysanpham;
    private javax.swing.JLabel lbl_thongke;
    private javax.swing.JLabel lbl_tinhluong;
    private javax.swing.JPanel panelHeader;
    // End of variables declaration//GEN-END:variables
    public void setButtonColor(javax.swing.JPanel selectedButton, JLabel label, JPanel panelShow) {
        Color selectColor = new Color(0, 0, 0);
        Color defaultColor = new Color(51, 51, 51);
        Color lblColor = new Color(153,153,153);
        btn_qlynhanvien.setBackground(defaultColor);
        btn_qlysanpham.setBackground(defaultColor);
        btn_thongke.setBackground(defaultColor);
        btn_tinhluong.setBackground(defaultColor);
        
        selectedButton.setBackground(selectColor);
        
        
        lbl_tinhluong.setForeground(lblColor);
        lbl_qlynhanvien.setForeground(lblColor);
        lbl_qlysanpham.setForeground(lblColor);
        lbl_thongke.setForeground(lblColor);
        label.setForeground(new Color(204,0,51));
        
        Panel_Main.removeAll();
        Panel_Main.setLayout(new BorderLayout());
        Panel_Main.add(panelShow, BorderLayout.CENTER);
        Panel_Main.revalidate();
        Panel_Main.repaint();

    }

}
